# Start from a base Java image
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy the built JAR file
COPY target/money_map-0.0.1-SNAPSHOT.jar app.jar

# Expose port (must match the port your app runs on, usually 8080)
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
